# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-fernschreiber

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^(libtdjson|libopenh264).*$
%define _binary_payload w6.xzdio

Summary:    Fernschreiber is a Telegram client for Sailfish OS
Version:    0.18
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://werkwolf.eu/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-fernschreiber.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   nemo-qml-plugin-contacts-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Positioning)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  gperf
BuildRequires:  desktop-file-utils

%description
Fernschreiber is a Telegram client for Sailfish OS


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5  \
    %{?_with_voicecalls:CONFIG+=voicecalls} %{?tg_owt_root:TG_OWT_ROOT=%{tg_owt_root}} %{?tgcalls_root:TGCALLS_ROOT=%{tgcalls_root}} %{?openh264_root:OPENH264_ROOT=%{openh264_root}}

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# Only built with "--with voicecalls": the PulseAudio policy rule that keeps the
# WebRTC call streams out of the corking "othermedia" group (doc/voicecalls.md).
%if 0%{?_with_voicecalls:1}
%config %{_sysconfdir}/pulse/xpolicy.conf.d/%{name}.conf
%endif
# << files
